### ISSUE TITLE
Кнопочка "скачать как csv" в истории

### ISSUE THREAD

**Issue by evgeny-boger** [contactless/homeui#116]

**Comment by pavel-rakhmanov** [comment]
@evgeny-boger, я реализовал функциональность скачивания таблиц с историей в .csv формате, есть только вопрос по желаемому расположению и оформлению кнопки (пока вот так)
![image](https://user-images.githubusercontent.com/22203119/50975919-b953be80-14ff-11e9-8ac3-f2399c8f9889.png)
И по названию результирующего файла - должно ли оно содержать название каналов/время? Просто иногда названия каналов очень длинные, а у файлов есть ограничения на длину названий (255 для Windows) и назвать файл с 3+ устройствами с длинными именами красиво уже будет невозможно.
