### ISSUE TITLE
Логотпы и favicon

### ISSUE THREAD

**Issue by evgeny-boger** [contactless/homeui#54]
Нужно добавить правильные фавиконку, вместо Wiren Board WEB UI вставить наш логотип с доской, убрать Carbonfay и Contactless с каждой странички

**Comment by DDmitiy** [comment]
Где можно взять исходник логотипа?

**Comment by poglazoff** [comment]
![2](https://user-images.githubusercontent.com/1129843/46741498-d339f700-ccad-11e8-9252-e5bd5b363d57.png)

**Comment by evgeny-boger** [comment]
[wirenboard_logo_round.zip](https://github.com/contactless/homeui/files/2473830/wirenboard_logo_round.zip)
