### ISSUE TITLE
Кнопка "удалить retained"

### ISSUE THREAD

**Issue by evgeny-boger** [contactless/homeui#55]
У каждого блока в Devices нужно добавить кнопочку, которая "удаляет" устройство. Удаление должно быть после всплывающего подтверждающего модального окна.

Что такое удаление: нужно взять все известные топики устройства, включая мета-топики и отправить в них (publish) строку нулевой длины с флагом retain и qos=2.

**Comment by pavel-rakhmanov** [comment]
@evgeny-boger, у меня при работе по этой задаче возникла вопросы:

Вы пишете про метод `publish` в issue? Просто в файле `mqttService.js` есть такой метод, который является обёрткой над методом `client.publish()` где `client` - экземпляр класса `Paho.MQTT.Client`. И у него нет метода `publish`. Т.е. `mqttService.publish` просто пытается вызвать undefined и нигде в проекте не используется..

Я в [коммите](https://github.com/contactless/homeui/commit/827ed1940cbbd8d37791deb7c345cac928c42474) попытался собрать все топики устройства, и потом во все просто отправляю `mqttClient.send()` сообщение, как написано в теле issue.
Как мне тестировать удаление устройств? Есть возможность наплодить несколько тестовых для удаления, а то кажется добавление устройства мне самому не сделать.

**Comment by evgeny-boger** [comment]
ээ, что? Когда на кнопочку юзер нажимает - сообщение в MQTT же кто-то отправляет. Отправка сообщений в терминах MQTT называется "publish". Как называются методы в библиотеке я не знаю.

Прочитай пожалуйста https://mosquitto.org/man/mqtt-7.html - тут две странички всего, так, думаю, будет сильно понятнее что вообще у нас происходит в интерфейсе и что я хочу в этом топике.

**Comment by evgeny-boger** [comment]
bq. Как мне тестировать удаление устройств? Есть возможность наплодить несколько тестовых для удаления, а то кажется добавление устройства мне самому не сделать.

google: mqtt websocket client, в онлайне куча. Реквизиты как я давал. Топики указывать с префиксом, т.е.  /client/<LOGIN>/devices/blah/controls/blah

Тут подробно про формат топиков https://github.com/contactless/homeui/blob/master/conventions.md

Соответственно создать устройство - это отправить несколько retain сообщений в несколько топиков, после этого устройство появится в интерфейсе. Удаление - в топики отправится null, из интерфейса они пропадут.
