### ISSUE TITLE
Передалать раздел Devices

### ISSUE THREAD

**Issue by evgeny-boger** [contactless/homeui#56]
Он сейчас сильно тормозит даже не столько из-за ангуляра, сколько из-за браузеров. Нужно как-то предусмотреть отображение многих девайсов одновременно. Предложение - сделать это таблицей, типа как в Widgets или MQTT Channels, в которой подряд идут каналы, объёдинённые в секции (заголовки) по устройствам. Устройства можно сворачивать, тогда они перестают рисоваться (т.е. не просто скрываются с глаз, а ангуляр их правда не перерисовывает).

При этом если все каналы не помещаются в два экрана или их больше какого-то числа, то устройства должны быть по-умолчанию свёрнуты кроме одного. Это первое устройство в списке, либо заданное в пути в url за решёточкой, чтобы можно было бы делать "ссылки" на открытое определённое устройство.

**Comment by pavel-rakhmanov** [comment]
@evgeny-boger, переделывать именно на таблицы, или вот в angular-ui, библиотеке что используется в проекте есть красивые сворачиваемые элементы - https://angular-ui.github.io/bootstrap/#accordion.
Можно их подвести под текущий стиль виджетов и визуально ничего не изменится, просто они научатся калапситься. А когда они сворачиваются как раз не отрисовывать их содержимое для экономии ресурсов браузер.

**Comment by evgeny-boger** [comment]
@pavel-rakhmanov Давай, да

**Comment by pavel-rakhmanov** [comment]
@evgeny-boger, сейчас в ветке `WB#56-remake_devices_screen` переделан экран с девайсами:
+ сделано отображение через компонент accordion из UI библиотеки angular-ui
+ использование новых компонентов angular-ui исправило отображение свичей на desctop разрешении
 + при количестве устройств более чем N штук (константа в коде) все устройства кроме 1 будут по умолчанию свёрнуты
+ при переходе по url вида `/#!/devices/device_id` отображается развернутым только указанное устройство
+ состояния раскрытия сохраняются при переходе между страницами

![new-devices-page](https://user-images.githubusercontent.com/22203119/47378051-a18a4c80-d6ff-11e8-98a0-da7f6c1915bf.png)

Но есть и сложности с:
- состояния раскрытия не сохраняются после перезагрузок страниц
- устройства пока распределены по колонкам как это было раньше 

Можете посмотреть производительность (которая и была целью исправлений) и в целом соответствие поведения ожидаемому?

**Comment by evgeny-boger** [comment]
У меня почему-то открывается в одну колонку и не сворачивается, свежий хромиум. Что проверить?

**Comment by pavel-rakhmanov** [comment]
`git pull`. В двух коммитах, запушеных 15 минут назад было добавлено отображение в колонках и улучшена проверка состояния открытия устройства.
