### ISSUE TITLE
Текст и неизвестные типы каналов показывать текстом, а не textbox-ом

### ISSUE THREAD

**Issue by evgeny-boger** [contactless/homeui#66]
![image](https://user-images.githubusercontent.com/1755320/46814733-051c8d80-cd82-11e8-9ec1-3d0b2123efe6.png)

Вот тут видно, что часть - это поля ввода, так быть не должно.

**Comment by pavel-rakhmanov** [comment]
@evgeny-boger, сейчас все `display-cell`'s с параметром ` displayType === text `
рендерятся с помощью input'ов (компонта `textCell`). Есть где-то моменты, когда действительно должен быть input а не текст? От чего это должно зависеть? Что такое 
> неизвестные типы каналов

**Comment by evgeny-boger** [comment]
1) Нет, если это readonly, то не нужно делать input
2) Изначально есть каналы в MQTT, у который есть meta type (см. https://wirenboard.com/wiki/index.php/MQTT https://github.com/contactless/homeui/blob/master/conventions.md)

сейчас интерфейс, если встречает неизвестный ему тип, отрисовывает его как text, если я правильно понимаю
