### ISSUE TITLE
Переименовать раздел Scripts в Rules

### ISSUE THREAD

**Issue by poglazoff** [contactless/homeui#85]

**Comment by pavel-rakhmanov** [comment]
@evgeny-boger, вот тут какая глубина переименования требуется? Просто в меню и rout'инге? 
```
      url: '/rules',
      controller: 'ScriptsCtrl as $ctrl',
      templateUrl: 'views/scripts.html',
```
Или сами контроллеры, их содержимое и переменные, что-бы в rule.controller не встречались вдруг scripts?

**Comment by evgeny-boger** [comment]
Только пункт в меню, да
