### ISSUE TITLE
Удалить неработающие элементы в Scrtipts

### ISSUE THREAD

**Issue by evgeny-boger** [contactless/homeui#86]
всё это 
![image](https://user-images.githubusercontent.com/1755320/48114740-40bb5200-e271-11e8-9012-5e21a5d9ce98.png)

не поддержано бэкендом, надо убрать.

**Comment by Yanni66** [comment]
Ну мусорное ведро то работает! Может оставить?

**Comment by pavel-rakhmanov** [comment]
Хорошо, верну. (Задача сделана, она пока на review у Дмитрия)
